# Generated by Django 5.0.4 on 2024-04-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='foto',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
